# my-verilog-examples task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: my-verilog-examples

outputs:
  - name: my-verilog-examples-updated

run:
  path: ./my-verilog-examples/ci/scripts/readme-github-pages.sh
  # args: [-debug]
